$schema: https://json-schema.org/draft/2020-12/schema
description: provenance chain
$defs:
  objectref:
    $anchor: objectref
    $ref: https://opengeospatial.github.io/bblocks/annotated-schemas/ogc-utils/iri-or-curie/schema.json
  oneOrMoreObjectref:
    $ref: https://opengeospatial.github.io/bblocks/annotated-schemas/ogc-utils/iri-or-curie/schema.json#/$defs/MultipleOrObject
  oneOrMoreActivitiesOrRefIds:
    oneOf:
      - $ref: '#/$defs/objectref'
      - $ref: '#/$defs/Activity'
      - type: array
        items:
          anyOf:
            - $ref: '#/$defs/objectref'
            - $ref: '#/$defs/Activity'
  oneOrMoreEntitiesOrRefIds:
    oneOf:
      - $ref: '#/$defs/objectref'
      - $ref: '#/$defs/Entity'
      - type: array
        items:
          anyOf:
            - $ref: '#/$defs/objectref'
            - $ref: '#/$defs/Entity'
  oneOrMoreAgentsOrRefIds:
    oneOf:
      - $ref: '#/$defs/objectref'
      - $ref: '#/$defs/externalLink'
      - $ref: '#/$defs/Agent'
      - type: array
        items:
          anyOf:
            - $ref: '#/$defs/objectref'
            - $ref: '#/$defs/Agent'
  externalLink:
    $ref: https://opengeospatial.github.io/bblocks/annotated-schemas/ogc-utils/json-link/schema.json
  influenced:
    type: object
    properties:
      wasInfluencedBy:
        anyOf:
          - $ref: '#/$defs/oneOrMoreActivitiesOrRefIds'
          - $ref: '#/$defs/oneOrMoreEntitiesOrRefIds'
          - $ref: '#/$defs/oneOrMoreAgentsOrRefIds'
      qualifiedInfluence:
        oneOf:
          - $ref: '#/$defs/objectref'
          - $ref: '#/$defs/Influence'
          - type: array
            items:
              oneOf:
                - $ref: '#/$defs/objectref'
                - $ref: '#/$defs/Influence'
  Entity:
    type: object
    properties:
      id:
        type: string
      featureType:
        $ref: '#/$defs/objectref'
      provenance:
        $ref: '#/$defs/Prov'
      wasGeneratedBy:
        $ref: '#/$defs/oneOrMoreActivitiesOrRefIds'
      wasAttributedTo:
        $ref: '#/$defs/oneOrMoreAgentsOrRefIds'
      wasDerivedFrom:
        $ref: '#/$defs/oneOrMoreEntitiesOrRefIds'
      alternateOf:
        $ref: '#/$defs/oneOrMoreEntitiesOrRefIds'
      hadPrimarySource:
        $ref: '#/$defs/oneOrMoreEntitiesOrRefIds'
      specializationOf:
        $ref: '#/$defs/oneOrMoreEntitiesOrRefIds'
      wasInvalidatedBy:
        $ref: '#/$defs/oneOrMoreAgentsOrRefIds'
      wasQuotedFrom:
        $ref: '#/$defs/oneOrMoreAgentsOrRefIds'
      wasRevisionOf:
        $ref: '#/$defs/oneOrMoreAgentsOrRefIds'
      mentionOf:
        $ref: '#/$defs/oneOrMoreAgentsOrRefIds'
      atLocation:
        $ref: '#/$defs/objectref'
      links:
        type: array
        items:
          $ref: '#/$defs/externalLink'
      qualifiedGeneration:
        oneOf:
          - $ref: '#/$defs/objectref'
          - $ref: '#/$defs/Generation'
          - type: array
            items:
              oneOf:
                - $ref: '#/$defs/objectref'
                - $ref: '#/$defs/Generation'
      qualifiedInvalidation:
        oneOf:
          - $ref: '#/$defs/objectref'
          - $ref: '#/$defs/Invalidation'
          - type: array
            items:
              oneOf:
                - $ref: '#/$defs/objectref'
                - $ref: '#/$defs/Invalidation'
      qualifiedDerivation:
        oneOf:
          - $ref: '#/$defs/objectref'
          - $ref: '#/$defs/Derivation'
          - type: array
            items:
              oneOf:
                - $ref: '#/$defs/objectref'
                - $ref: '#/$defs/Derivation'
      qualifiedAttribution:
        oneOf:
          - $ref: '#/$defs/objectref'
          - $ref: '#/$defs/Attribution'
          - type: array
            items:
              oneOf:
                - $ref: '#/$defs/objectref'
                - $ref: '#/$defs/Attribution'

    required:
      - id
    anyOf:
      - properties:
          type:
            oneOf:
              - type: string
                enum: [ Entity, Bundle, Plan ]
              - type: array
                contains:
                  type: string
                  enum: [ Entity, Bundle, Plan ]
        required:
          - type
      - required:
          - featureType
      - required:
          - wasGeneratedBy
      - required:
          - wasAttributedTo
      - required:
          - wasDerivedFrom
      - required:
          - provenance
      - properties:
          type:
            type: string
            const: Collection
          hadMember:
            type: array
            items:
              $ref: '#/$defs/Entity'
        required:
          - hadMember
          - type
      - properties:
          type:
            type: string
            const: EmptyCollection
          hadMember:
            type: array
            maxItems: 0
        required:
          - hadMember
          - type
    allOf:
      - $ref: '#/$defs/influenced'
  dateOrTime:
    oneOf:
      - type: string
        format: date
        pattern: ^\d{4}-\d{2}-\d{2}$
      - type: string
        format: date-time
        pattern: ^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(?:\.\d+)?(?:Z|[+-]\d{2}:\d{2})?$
  Activity:
    type: object
    properties:
      type:
        $ref: '#/$defs/oneOrMoreObjectref'
      endedAtTime:
        $ref: '#/$defs/dateOrTime'
      wasAssociatedWith:
        $ref: '#/$defs/oneOrMoreAgentsOrRefIds'
      wasInformedBy:
        $ref: '#/$defs/oneOrMoreActivitiesOrRefIds'
      used:
        $ref: '#/$defs/oneOrMoreEntitiesOrRefIds'
      wasStartedBy:
        $ref: '#/$defs/oneOrMoreEntitiesOrRefIds'
      wasEndedBy:
        $ref: '#/$defs/oneOrMoreEntitiesOrRefIds'
      invalidated:
        $ref: '#/$defs/oneOrMoreEntitiesOrRefIds'
      generated:
        $ref: '#/$defs/oneOrMoreEntitiesOrRefIds'
      atLocation:
        $ref: '#/$defs/objectref'
      qualifiedUsage:
        oneOf:
          - $ref: '#/$defs/objectref'
          - $ref: '#/$defs/Usage'
          - type: array
            items:
              oneOf:
                - $ref: '#/$defs/objectref'
                - $ref: '#/$defs/Usage'
      qualifiedCommunication:
        oneOf:
          - $ref: '#/$defs/objectref'
          - $ref: '#/$defs/Communication'
          - type: array
            items:
              oneOf:
                - $ref: '#/$defs/objectref'
                - $ref: '#/$defs/Generation'
      qualifiedStart:
        oneOf:
          - $ref: '#/$defs/objectref'
          - $ref: '#/$defs/Start'
      qualifiedEnd:
        oneOf:
          - $ref: '#/$defs/objectref'
          - $ref: '#/$defs/End'
      qualifiedAssociation:
        oneOf:
          - $ref: '#/$defs/objectref'
          - $ref: '#/$defs/Association'
          - type: array
            items:
              oneOf:
                - $ref: '#/$defs/objectref'
                - $ref: '#/$defs/Association'
    anyOf:
      - properties:
          type:
            oneOf:
              - type: string
                const: Activity
              - type: array
                contains:
                  type: string
                  const: Activity
                items:
                  type: string
        required:
          - type
      - required:
          - activity
      - required:
          - used
      - required:
          - wasInformedBy
      - required:
          - endedAtTime
      - required:
          - startedAtTime
      - required:
          - wasAssociatedWith
    allOf:
      - $ref: '#/$defs/influenced'
  Agent:
    type: object
    properties:
      type:
        $ref: '#/$defs/oneOrMoreObjectref'
      name:
        type: string
      id:
        type: string
        format: uri
      actedOnBehalfOf:
        $ref: '#/$defs/oneOrMoreAgentsOrRefIds'
      atLocation:
        $ref: '#/$defs/objectref'
      qualifiedDelegation:
        oneOf:
          - $ref: '#/$defs/objectref'
          - $ref: '#/$defs/Delegation'
          - type: array
            items:
              oneOf:
                - $ref: '#/$defs/objectref'
                - $ref: '#/$defs/Delegation'
    required:
      - name
    anyOf:
      - properties:
          type:
            oneOf:
              - type: string
                enum: [ Agent, Organization, Person, SoftwareAgent, SoftwareDescription, DirectQueryService ]
              - type: array
                contains:
                  type: string
                  enum: [ Agent, Organization, Person, SoftwareAgent, SoftwareDescription, DirectQueryService ]
                items:
                  type: string
        required:
          - type
      - required:
          - agentType
      - required:
          - actedOnBehalfOf
    allOf:
      - $ref: '#/$defs/influenced'
  Usage:
    type: object
    properties:
      type:
        oneOf:
          - type: string
            const: Usage
          - type: array
            contains:
              type: string
              const: Usage
            items:
              type: string
      atTime:
        $ref: '#/$defs/dateOrTime'
      entity:
        oneOf:
          - $ref: '#/$defs/objectref'
          - $ref: '#/$defs/Entity'
    required:
      - atTime
      - entity
  Generation:
    type: object
    properties:
      type:
        oneOf:
          - type: string
            const: Generation
          - type: array
            contains:
              type: string
              const: Generation
            items:
              type: string
      atTime:
        $ref: '#/$defs/dateOrTime'
      activity:
        oneOf:
          - $ref: '#/$defs/objectref'
          - $ref: '#/$defs/Activity'
    required:
      - atTime
      - activity
  Invalidation:
    type: object
    properties:
      type:
        oneOf:
          - type: string
            const: Invalidation
          - type: array
            contains:
              type: string
              const: Invalidation
            items:
              type: string
      atTime:
        $ref: '#/$defs/dateOrTime'
      activity:
        oneOf:
          - $ref: '#/$defs/objectref'
          - $ref: '#/$defs/Activity'
    required:
      - atTime
      - activity
  Communication:
    type: object
    properties:
      type:
        oneOf:
          - type: string
            const: Communication
          - type: array
            contains:
              type: string
              const: Communication
            items:
              type: string
      activity:
        oneOf:
          - $ref: '#/$defs/objectref'
          - $ref: '#/$defs/Activity'
    required:
      - activity
  StartOrEnd:
    type: object
    properties:
      type:
        oneOf:
          - type: string
          - type: array
            items:
              type: string
      atTime:
        $ref: '#/$defs/dateOrTime'
      entity:
        oneOf:
          - $ref: '#/$defs/objectref'
          - $ref: '#/$defs/Entity'
      hadActivity:
        oneOf:
          - $ref: '#/$defs/objectref'
          - $ref: '#/$defs/Activity'
  Start:
    allOf:
      - $ref: '#/$defs/StartOrEnd'
      - properties:
          type:
            oneOf:
              - const: Start
              - contains:
                  const: Start
  End:
    allOf:
      - $ref: '#/$defs/StartOrEnd'
      - properties:
          type:
            oneOf:
              - const: End
              - contains:
                  const: End
    required:
      - atTime
      - entity
  Derivation:
    type: object
    properties:
      type:
        oneOf:
          - type: string
            const: Derivation
          - type: array
            contains:
              type: string
              const: Derivation
            items:
              type: string
      hadGeneration:
        oneOf:
          - $ref: '#/$defs/objectref'
          - $ref: '#/$defs/Generation'
      hadActivity:
        oneOf:
          - $ref: '#/$defs/objectref'
          - $ref: '#/$defs/Activity'
      hadUsage:
        oneOf:
          - $ref: '#/$defs/objectref'
          - $ref: '#/$defs/Usage'
      entity:
        oneOf:
          - $ref: '#/$defs/objectref'
          - $ref: '#/$defs/Entity'
    required:
      - atTime
      - entity
  Delegation:
    type: object
    properties:
      type:
        oneOf:
          - type: string
            const: Delegation
          - type: array
            contains:
              type: string
              const: Delegation
            items:
              type: string
      agent:
        oneOf:
          - $ref: '#/$defs/objectref'
          - $ref: '#/$defs/Agent'
      hadActivity:
        oneOf:
          - $ref: '#/$defs/objectref'
          - $ref: '#/$defs/Activity'
    required:
      - agent
  Attribution:
    type: object
    properties:
      type:
        oneOf:
          - type: string
            const: Attribution
          - type: array
            contains:
              type: string
              const: Attribution
            items:
              type: string
      agent:
        oneOf:
          - $ref: '#/$defs/objectref'
          - $ref: '#/$defs/Agent'
    required:
      - agent
  Association:
    type: object
    properties:
      type:
        oneOf:
          - type: string
            const: Attribution
          - type: array
            contains:
              type: string
              const: Attribution
            items:
              type: string
      agent:
        oneOf:
          - $ref: '#/$defs/objectref'
          - $ref: '#/$defs/Agent'
      hadRole:
        $ref: '#/$defs/oneOrMoreObjectref'
      hadPlan:
        $ref: '#/$defs/oneOrMoreObjectref'
    required:
      - agent
  Influence:
    influencer:
      anyOf:
        - $ref: '#/$defs/oneOrMoreActivitiesOrRefIds'
        - $ref: '#/$defs/oneOrMoreEntitiesOrRefIds'
        - $ref: '#/$defs/oneOrMoreAgentsOrRefIds'
    entity:
      $ref: '#/$defs/oneOrMoreEntitiesOrRefIds'
    activity:
      $ref: '#/$defs/oneOrMoreActivitiesOrRefIds'
    agent:
      $ref: '#/$defs/oneOrMoreAgentsOrRefIds'
    anyOf:
      - required: [ influencer ]
      - required: [ entity ]
      - required: [ activity ]
      - required: [ agent ]
  Prov:
    description: An list of provenance objects linked together to form a provenance
      chain for the current object. Objects may have nested objects as well, with
      or without referencable ids
    type: array
    items:
      oneOf:
        - $ref: '#/$defs/Entity'
        - $ref: '#/$defs/Activity'
        - $ref: '#/$defs/Agent'
anyOf:
  - $ref: '#/$defs/Entity'
  - $ref: '#/$defs/Activity'
